language: c

env:
  matrix:
    - TEST_CALL="FIRST CALL"
    - TEST_CALL="SECOND CALL"
    - TEST_CALL="THIRD CALL"


jobs:
  include:
    - stage: test     
      script: gcc -c main.c && echo $TEST_CALL	
    - stage: deploy
      script: echo "Deploy"