language: c a
sudo: required

env:
  - TARGET_DIST=ubuntu TARGET_VERSION=1604 RTM_VERSION=1.0.0
  - TARGET_DIST=ubuntu TARGET_VERSION=1804 RTM_VERSION=1.0.0

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  
  
script:
  - echo $TARGET_DIST $TARGET_VERSION
  - 'if [ $TRAVIS_BRANCH = "master" ]; then
    echo "script master branch";
    docker --version
    bash script_master.sh ;
    fi'
  - 'if [ $TRAVIS_BRANCH = "test_branch" ]; then
    echo "script test branch";
    bash script_test.sh ;
    fi'

after_success:
    - 'if [ $TRAVIS_BUILD_STAGE_NAME = "Src_build" ]; then
         echo "after_success stage src_build";
       fi'
    - 'if [ $TRAVIS_BUILD_STAGE_NAME = "Test" ]; then
         echo "after_success stage test";
       fi'
    - 'if [ $TRAVIS_BUILD_STAGE_NAME = "Deploy" ]; then
         echo "after_success stage deploy";
       fi'

stages:
  - src_build
  - test
  - deploy




jobs:
  include:
    - stage: src_build
      script: echo "src_build"
    - stage: deploy
      script: echo "deploy job"

deploy:
  - provider: script
    script: echo "master"
    on:
      branch: master
  - provider: script
    script: echo "test_branch"
    on:
          branch: test_branch
