language: c
sudo: required

env:
  matrix:
  - TARGET_DIST=ubuntu TARGET_VERSION=1604 RTM_VERSION=1.0.0
  - TARGET_DIST=ubuntu TARGET_VERSION=1804 RTM_VERSION=1.0.0

jobs:
  include:
    - stage: test
      script: echo "state test"
    - stage: deploy
      script: echo "deploy"

script:
 - echo $TARGET_DIST $TARGET_VERSION
 



