language: c
sudo: required

env:
  - TARGET_DIST=ubuntu TARGET_VERSION=1604 RTM_VERSION=1.0.0
  - TARGET_DIST=ubuntu TARGET_VERSION=1804 RTM_VERSION=1.0.0

script:
 - echo $TARGET_DIST $TARGET_VERSION

stages:
  - src_build
  - test
  - deploy

jobs:
  include:
    - stage: test
      script: echo "test"
    - stage: src_build
      script: echo "src_build"
    - stage: deploy
      script: echo "deploy"


 



