language: c
sudo: required

before_script:
 - docker build -t test/test .
 - docker run -ti -d -v `pwd`:/work --name integ test/test 

env:
  matrix:
  - TEST_CALL="FIRST CALL"
  - TEST_CALL="SECOND CALL"
  - TEST_CALL="THIRD CALL"

#script: gcc -c main.c && echo $TEST_CALL
script:
 - cat /etc/os-release
 - docker exec -ti integ cat /etc/os-release
 - docker exec -ti integ ls

jobs:
  include:
    - stage: deploy
      script: echo "Deploy"