language: c
env:
  matrix:
  - TEST_CALL="FIRST CALL"
  - TEST_CALL="SECOND CALL"
  - TEST_CALL="THIRD CALL"

script: gcc -c main.c && echo $TEST_CALL			

jobs:
  include:
    - stage: deploy
      script: echo "Deploy"