language: c
sudo: required

before_script:
 - openssl aes-256-cbc -K $encrypted_31d12b5c5a08_key -iv $encrypted_31d12b5c5a08_iv -in id_rsa.enc -out ~\/.ssh/id_rsa -d
 - docker build -t test/test .
 - docker run -ti -d -v $TRAVIS_BUILD_DIR:/work --name integ test/test 


env:
  matrix:
  - TEST_CALL="FIRST CALL"
  - TEST_CALL="SECOND CALL"
  - TEST_CALL="THIRD CALL"

script:
 - echo $TEST_CALL
 - docker exec -ti integ cat /etc/os-release
 - docker exec -ti integ gcc -o work/release_app work/tmp/main.c
 - ./release_app
 

jobs:
  include:
    - stage: deploy
      script: echo "Deploy"